name: Fast API CI and Docker Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build app and run test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/checkout@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Fast API
        run: |
          export ENV="build"
          docker build --target production -t prod-fastapi . 
          docker run -p 8000:8000 prod-fastapi

      - name: Run unit tests
        run: pytest

      - name: Docker Container Stop
        run: docker stop prod-fastapi
