name: Fast API CI and Docker Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build app and run test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/checkout@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Docker Compose
        run: |
          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          docker-compose up -d

      - name: Run unit tests
        run: pytest

      - name: Stop Docker Compose
        run: docker-compose down
